import { fromWorkspace, LiteSVMProvider } from "anchor-litesvm";
import { Program, BN } from "@coral-xyz/anchor";
import { Keypair, PublicKey, SystemProgram } from "@solana/web3.js";
import { expect } from "chai";
import { createRequire } from "module";

// Load the IDL generated by `anchor build`.
// Use createRequire for compatibility with both CJS and ESM execution modes.
const require = createRequire(import.meta.url);
const IDL = require("../target/idl/guardrails.json");

describe("guardrails", () => {
  // Boot an in-process Solana VM from the workspace (loads .so from target/)
  const svm = fromWorkspace(".");
  const provider = new LiteSVMProvider(svm);
  const program = new Program(IDL, provider);

  // Shared keypairs reused across tests
  const owner = Keypair.generate();
  const agent = Keypair.generate();

  // ---------------------------------------------------------------------------
  // PDA derivation helpers
  // ---------------------------------------------------------------------------

  function findPolicyPda(
    ownerKey: PublicKey,
    agentKey: PublicKey
  ): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
      [Buffer.from("policy"), ownerKey.toBuffer(), agentKey.toBuffer()],
      program.programId
    );
  }

  function findTrackerPda(policyKey: PublicKey): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
      [Buffer.from("tracker"), policyKey.toBuffer()],
      program.programId
    );
  }

  // ---------------------------------------------------------------------------
  // Default args for initialize_policy (reused across tests)
  // ---------------------------------------------------------------------------

  const defaultAllowedPrograms = [SystemProgram.programId];
  const defaultMaxTxLamports = new BN(1_000_000_000); // 1 SOL
  const defaultMaxTxTokenUnits = new BN(1_000_000);
  const defaultDailyBudgetLamports = new BN(5_000_000_000); // 5 SOL
  // Session expiry: ~1 year from now (safe for tests)
  const defaultSessionExpiry = new BN(
    Math.floor(Date.now() / 1000) + 365 * 24 * 60 * 60
  );
  const defaultEscalationThreshold = new BN(2_000_000_000); // 2 SOL

  // ---------------------------------------------------------------------------
  // Setup
  // ---------------------------------------------------------------------------

  before(() => {
    // Airdrop SOL to owner for rent + transaction fees
    svm.airdrop(owner.publicKey, 10_000_000_000n); // 10 SOL
  });

  // =========================================================================
  // initialize_policy
  // =========================================================================

  describe("initialize_policy", () => {
    it("creates policy and tracker PDAs with correct field values", async () => {
      const [policyPda] = findPolicyPda(owner.publicKey, agent.publicKey);
      const [trackerPda] = findTrackerPda(policyPda);
      const monitor1 = Keypair.generate().publicKey;

      await program.methods
        .initializePolicy({
          allowedPrograms: defaultAllowedPrograms,
          maxTxLamports: defaultMaxTxLamports,
          maxTxTokenUnits: defaultMaxTxTokenUnits,
          dailyBudgetLamports: defaultDailyBudgetLamports,
          sessionExpiry: defaultSessionExpiry,
          squadsMultisig: null,
          escalationThreshold: defaultEscalationThreshold,
          authorizedMonitors: [monitor1],
        })
        .accounts({
          owner: owner.publicKey,
          agent: agent.publicKey,
          policy: policyPda,
          spendTracker: trackerPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([owner])
        .rpc();

      // --- Verify PermissionPolicy fields ---
      const policy = await program.account.permissionPolicy.fetch(policyPda);

      expect(policy.owner.toBase58()).to.equal(owner.publicKey.toBase58());
      expect(policy.agent.toBase58()).to.equal(agent.publicKey.toBase58());

      // Allow-list should contain exactly the System Program
      expect(policy.allowedPrograms).to.have.lengthOf(1);
      expect(policy.allowedPrograms[0].toBase58()).to.equal(
        SystemProgram.programId.toBase58()
      );

      // Spending limits
      expect(policy.maxTxLamports.toNumber()).to.equal(1_000_000_000);
      expect(policy.maxTxTokenUnits.toNumber()).to.equal(1_000_000);
      expect(policy.dailyBudgetLamports.toNumber()).to.equal(5_000_000_000);
      expect(policy.dailySpentLamports.toNumber()).to.equal(0);

      // Session + status
      expect(policy.sessionExpiry.toNumber()).to.equal(
        defaultSessionExpiry.toNumber()
      );
      expect(policy.isActive).to.be.true;
      expect(policy.pausedBy).to.be.null;

      // Squads config
      expect(policy.squadsMultisig).to.be.null;
      expect(policy.escalationThreshold.toNumber()).to.equal(2_000_000_000);

      // Monitors
      expect(policy.authorizedMonitors).to.have.lengthOf(1);
      expect(policy.authorizedMonitors[0].toBase58()).to.equal(
        monitor1.toBase58()
      );

      // Defaults
      expect(policy.anomalyScore).to.equal(0);

      // --- Verify SpendTracker fields ---
      const tracker = await program.account.spendTracker.fetch(trackerPda);

      expect(tracker.policy.toBase58()).to.equal(policyPda.toBase58());
      // Note: Anchor camelCase converts `_24h` suffix to `24H` (capital H)
      expect((tracker as any).txnCount24H).to.equal(0);
      expect((tracker as any).lamportsSpent24H.toNumber()).to.equal(0);
      expect(tracker.lastTxnTs.toNumber()).to.equal(0);
    });

    it("fails when initializing duplicate policy for same owner+agent", async () => {
      // The first init ran in the previous test — same (owner, agent) PDA exists
      const [policyPda] = findPolicyPda(owner.publicKey, agent.publicKey);
      const [trackerPda] = findTrackerPda(policyPda);

      try {
        await program.methods
          .initializePolicy({
            allowedPrograms: defaultAllowedPrograms,
            maxTxLamports: defaultMaxTxLamports,
            maxTxTokenUnits: defaultMaxTxTokenUnits,
            dailyBudgetLamports: defaultDailyBudgetLamports,
            sessionExpiry: defaultSessionExpiry,
            squadsMultisig: null,
            escalationThreshold: defaultEscalationThreshold,
            authorizedMonitors: [],
          })
          .accounts({
            owner: owner.publicKey,
            agent: agent.publicKey,
            policy: policyPda,
            spendTracker: trackerPda,
            systemProgram: SystemProgram.programId,
          })
          .signers([owner])
          .rpc();

        expect.fail("Expected duplicate init to fail");
      } catch (err: any) {
        // Anchor rejects init on an already-initialized account
        expect(err).to.exist;
      }
    });

    it("fails when allowed_programs exceeds max (10)", async () => {
      const freshAgent = Keypair.generate();
      const [policyPda] = findPolicyPda(owner.publicKey, freshAgent.publicKey);
      const [trackerPda] = findTrackerPda(policyPda);

      // 11 programs exceeds MAX_ALLOWED_PROGRAMS = 10
      const tooManyPrograms = Array.from({ length: 11 }, () =>
        Keypair.generate().publicKey
      );

      try {
        await program.methods
          .initializePolicy({
            allowedPrograms: tooManyPrograms,
            maxTxLamports: defaultMaxTxLamports,
            maxTxTokenUnits: defaultMaxTxTokenUnits,
            dailyBudgetLamports: defaultDailyBudgetLamports,
            sessionExpiry: defaultSessionExpiry,
            squadsMultisig: null,
            escalationThreshold: defaultEscalationThreshold,
            authorizedMonitors: [],
          })
          .accounts({
            owner: owner.publicKey,
            agent: freshAgent.publicKey,
            policy: policyPda,
            spendTracker: trackerPda,
            systemProgram: SystemProgram.programId,
          })
          .signers([owner])
          .rpc();

        expect.fail("Expected TooManyAllowedPrograms error");
      } catch (err: any) {
        expect(err.toString()).to.include("TooManyAllowedPrograms");
      }
    });

    it("fails when max_tx_lamports exceeds daily_budget_lamports", async () => {
      const freshAgent = Keypair.generate();
      const [policyPda] = findPolicyPda(owner.publicKey, freshAgent.publicKey);
      const [trackerPda] = findTrackerPda(policyPda);

      try {
        await program.methods
          .initializePolicy({
            allowedPrograms: defaultAllowedPrograms,
            maxTxLamports: new BN(10_000_000_000), // 10 SOL per tx...
            maxTxTokenUnits: defaultMaxTxTokenUnits,
            dailyBudgetLamports: new BN(5_000_000_000), // ...but only 5 SOL daily
            sessionExpiry: defaultSessionExpiry,
            squadsMultisig: null,
            escalationThreshold: defaultEscalationThreshold,
            authorizedMonitors: [],
          })
          .accounts({
            owner: owner.publicKey,
            agent: freshAgent.publicKey,
            policy: policyPda,
            spendTracker: trackerPda,
            systemProgram: SystemProgram.programId,
          })
          .signers([owner])
          .rpc();

        expect.fail("Expected TxLimitExceedsDailyBudget error");
      } catch (err: any) {
        expect(err.toString()).to.include("TxLimitExceedsDailyBudget");
      }
    });
  });

  // =========================================================================
  // update_policy
  // =========================================================================

  describe("update_policy", () => {
    it("owner can update limits and verify changes", async () => {
      const [policyPda] = findPolicyPda(owner.publicKey, agent.publicKey);

      const newProgram = Keypair.generate().publicKey;
      const newMonitor = Keypair.generate().publicKey;

      await program.methods
        .updatePolicy({
          allowedPrograms: [SystemProgram.programId, newProgram],
          maxTxLamports: new BN(2_000_000_000), // 2 SOL
          maxTxTokenUnits: new BN(2_000_000),
          dailyBudgetLamports: new BN(10_000_000_000), // 10 SOL
          sessionExpiry: null, // unchanged
          squadsMultisig: null, // unchanged
          escalationThreshold: new BN(5_000_000_000), // 5 SOL
          authorizedMonitors: [newMonitor],
          anomalyScore: 42,
        })
        .accounts({
          owner: owner.publicKey,
          policy: policyPda,
        })
        .signers([owner])
        .rpc();

      const policy = await program.account.permissionPolicy.fetch(policyPda);

      // Updated fields
      expect(policy.allowedPrograms).to.have.lengthOf(2);
      expect(policy.allowedPrograms[1].toBase58()).to.equal(
        newProgram.toBase58()
      );
      expect(policy.maxTxLamports.toNumber()).to.equal(2_000_000_000);
      expect(policy.maxTxTokenUnits.toNumber()).to.equal(2_000_000);
      expect(policy.dailyBudgetLamports.toNumber()).to.equal(10_000_000_000);
      expect(policy.escalationThreshold.toNumber()).to.equal(5_000_000_000);
      expect(policy.authorizedMonitors).to.have.lengthOf(1);
      expect(policy.authorizedMonitors[0].toBase58()).to.equal(
        newMonitor.toBase58()
      );
      expect(policy.anomalyScore).to.equal(42);

      // Unchanged fields (passed as null → None → no update)
      expect(policy.sessionExpiry.toNumber()).to.equal(
        defaultSessionExpiry.toNumber()
      );
    });

    it("non-owner cannot update policy", async () => {
      const attacker = Keypair.generate();
      svm.airdrop(attacker.publicKey, 1_000_000_000n); // 1 SOL for fees

      const [policyPda] = findPolicyPda(owner.publicKey, agent.publicKey);

      try {
        await program.methods
          .updatePolicy({
            allowedPrograms: null,
            maxTxLamports: new BN(999_999_999),
            maxTxTokenUnits: null,
            dailyBudgetLamports: null,
            sessionExpiry: null,
            squadsMultisig: null,
            escalationThreshold: null,
            authorizedMonitors: null,
            anomalyScore: null,
          })
          .accounts({
            owner: attacker.publicKey,
            policy: policyPda,
          })
          .signers([attacker])
          .rpc();

        expect.fail("Expected non-owner update to fail");
      } catch (err: any) {
        // has_one constraint rejects because attacker.key != policy.owner
        expect(err).to.exist;
      }
    });

    it("fails when updating allowed_programs above max (10)", async () => {
      const [policyPda] = findPolicyPda(owner.publicKey, agent.publicKey);

      // 11 programs exceeds MAX_ALLOWED_PROGRAMS = 10
      const tooManyPrograms = Array.from({ length: 11 }, () =>
        Keypair.generate().publicKey
      );

      try {
        await program.methods
          .updatePolicy({
            allowedPrograms: tooManyPrograms,
            maxTxLamports: null,
            maxTxTokenUnits: null,
            dailyBudgetLamports: null,
            sessionExpiry: null,
            squadsMultisig: null,
            escalationThreshold: null,
            authorizedMonitors: null,
            anomalyScore: null,
          })
          .accounts({
            owner: owner.publicKey,
            policy: policyPda,
          })
          .signers([owner])
          .rpc();

        expect.fail("Expected TooManyAllowedPrograms error");
      } catch (err: any) {
        expect(err.toString()).to.include("TooManyAllowedPrograms");
      }
    });
  });

  // =========================================================================
  // Placeholder tests for future phases
  // =========================================================================

  // TODO: guarded_execute happy path — System Program SOL transfer succeeds
  // TODO: guarded_execute rejection — wrong program, over limit, expired session, paused
  // TODO: pause_agent — authorized monitor can pause, unauthorized cannot
  // TODO: resume_agent — only owner, not monitor
  // TODO: SpendTracker — partial spends, rollover at 24h, exceeding daily budget
  // TODO: escalate_to_squads — amount above threshold triggers proposal
});
