import { fromWorkspace, LiteSVMProvider } from "anchor-litesvm";
import { Program, BN } from "@coral-xyz/anchor";
import { Keypair, PublicKey, SystemProgram, Transaction } from "@solana/web3.js";
import { expect } from "chai";
import { createRequire } from "module";
import { Clock } from "litesvm";
import {
  TOKEN_PROGRAM_ID,
  MINT_SIZE,
  ACCOUNT_SIZE,
  createInitializeMintInstruction,
  createInitializeAccountInstruction,
  createMintToInstruction,
} from "@solana/spl-token";

// Load the IDL generated by `anchor build`.
// Use createRequire for compatibility with both CJS and ESM execution modes.
const require = createRequire(import.meta.url);
const IDL = require("../target/idl/guardrails.json");

describe("guardrails", () => {
  // Boot an in-process Solana VM from the workspace (loads .so from target/).
  // withDefaultPrograms() adds SPL Token Program so Token CPI tests work.
  const svm = fromWorkspace(".").withDefaultPrograms();
  const provider = new LiteSVMProvider(svm);
  const program = new Program(IDL, provider);

  // Shared keypairs reused across tests
  const owner = Keypair.generate();
  const agent = Keypair.generate();

  // ---------------------------------------------------------------------------
  // PDA derivation helpers
  // ---------------------------------------------------------------------------

  function findPolicyPda(
    ownerKey: PublicKey,
    agentKey: PublicKey
  ): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
      [Buffer.from("policy"), ownerKey.toBuffer(), agentKey.toBuffer()],
      program.programId
    );
  }

  function findTrackerPda(policyKey: PublicKey): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
      [Buffer.from("tracker"), policyKey.toBuffer()],
      program.programId
    );
  }

  // ---------------------------------------------------------------------------
  // Token Program helpers (for CPI happy-path tests)
  // ---------------------------------------------------------------------------

  async function createTestMint(
    mintKeypair: Keypair,
    authority: PublicKey,
    decimals: number = 6,
  ): Promise<PublicKey> {
    const rentExempt = svm.minimumBalanceForRentExemption(BigInt(MINT_SIZE));
    const tx = new Transaction().add(
      SystemProgram.createAccount({
        fromPubkey: provider.wallet.publicKey,
        newAccountPubkey: mintKeypair.publicKey,
        space: MINT_SIZE,
        lamports: Number(rentExempt),
        programId: TOKEN_PROGRAM_ID,
      }),
      createInitializeMintInstruction(mintKeypair.publicKey, decimals, authority, null),
    );
    await provider.sendAndConfirm!(tx, [mintKeypair]);
    return mintKeypair.publicKey;
  }

  async function createTestTokenAccount(
    accountKeypair: Keypair,
    mint: PublicKey,
    owner: PublicKey,
  ): Promise<PublicKey> {
    const rentExempt = svm.minimumBalanceForRentExemption(BigInt(ACCOUNT_SIZE));
    const tx = new Transaction().add(
      SystemProgram.createAccount({
        fromPubkey: provider.wallet.publicKey,
        newAccountPubkey: accountKeypair.publicKey,
        space: ACCOUNT_SIZE,
        lamports: Number(rentExempt),
        programId: TOKEN_PROGRAM_ID,
      }),
      createInitializeAccountInstruction(accountKeypair.publicKey, mint, owner),
    );
    await provider.sendAndConfirm!(tx, [accountKeypair]);
    return accountKeypair.publicKey;
  }

  async function mintTestTokens(
    mint: PublicKey,
    destination: PublicKey,
    mintAuthority: Keypair,
    amount: bigint,
  ): Promise<void> {
    const tx = new Transaction().add(
      createMintToInstruction(mint, destination, mintAuthority.publicKey, amount),
    );
    await provider.sendAndConfirm!(tx, [mintAuthority]);
  }

  function buildTokenTransferData(amount: bigint): Buffer {
    // Token Program Transfer: byte 0 = discriminator (3), bytes 1-8 = u64 amount
    const buf = Buffer.alloc(9);
    buf.writeUInt8(3, 0);
    buf.writeBigUInt64LE(amount, 1);
    return buf;
  }

  function getTokenBalance(tokenAccount: PublicKey): bigint {
    const accountInfo = svm.getAccount(tokenAccount);
    if (!accountInfo) throw new Error(`Token account ${tokenAccount.toBase58()} not found`);
    // SPL token account layout: bytes 64-71 = u64 amount (little-endian)
    const data = Buffer.from(accountInfo.data);
    return data.readBigUInt64LE(64);
  }

  // ---------------------------------------------------------------------------
  // Default args for initialize_policy (reused across tests)
  // ---------------------------------------------------------------------------

  const defaultAllowedPrograms = [SystemProgram.programId];
  const defaultMaxTxLamports = new BN(1_000_000_000); // 1 SOL
  const defaultMaxTxTokenUnits = new BN(1_000_000);
  const defaultDailyBudgetLamports = new BN(5_000_000_000); // 5 SOL
  // Session expiry: ~1 year from now (safe for tests)
  const defaultSessionExpiry = new BN(
    Math.floor(Date.now() / 1000) + 365 * 24 * 60 * 60
  );
  const defaultEscalationThreshold = new BN(2_000_000_000); // 2 SOL

  // ---------------------------------------------------------------------------
  // Setup
  // ---------------------------------------------------------------------------

  before(() => {
    // Airdrop SOL to owner for rent + transaction fees
    svm.airdrop(owner.publicKey, 10_000_000_000n); // 10 SOL
  });

  // =========================================================================
  // initialize_policy
  // =========================================================================

  describe("initialize_policy", () => {
    it("creates policy and tracker PDAs with correct field values", async () => {
      const [policyPda] = findPolicyPda(owner.publicKey, agent.publicKey);
      const [trackerPda] = findTrackerPda(policyPda);
      const monitor1 = Keypair.generate().publicKey;

      await program.methods
        .initializePolicy({
          allowedPrograms: defaultAllowedPrograms,
          maxTxLamports: defaultMaxTxLamports,
          maxTxTokenUnits: defaultMaxTxTokenUnits,
          dailyBudgetLamports: defaultDailyBudgetLamports,
          sessionExpiry: defaultSessionExpiry,
          squadsMultisig: null,
          escalationThreshold: defaultEscalationThreshold,
          authorizedMonitors: [monitor1],
        })
        .accounts({
          owner: owner.publicKey,
          agent: agent.publicKey,
          policy: policyPda,
          spendTracker: trackerPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([owner])
        .rpc();

      // --- Verify PermissionPolicy fields ---
      const policy = await program.account.permissionPolicy.fetch(policyPda);

      expect(policy.owner.toBase58()).to.equal(owner.publicKey.toBase58());
      expect(policy.agent.toBase58()).to.equal(agent.publicKey.toBase58());

      // Allow-list should contain exactly the System Program
      expect(policy.allowedPrograms).to.have.lengthOf(1);
      expect(policy.allowedPrograms[0].toBase58()).to.equal(
        SystemProgram.programId.toBase58()
      );

      // Spending limits
      expect(policy.maxTxLamports.toNumber()).to.equal(1_000_000_000);
      expect(policy.maxTxTokenUnits.toNumber()).to.equal(1_000_000);
      expect(policy.dailyBudgetLamports.toNumber()).to.equal(5_000_000_000);
      expect(policy.dailySpentLamports.toNumber()).to.equal(0);

      // Session + status
      expect(policy.sessionExpiry.toNumber()).to.equal(
        defaultSessionExpiry.toNumber()
      );
      expect(policy.isActive).to.be.true;
      expect(policy.pausedBy).to.be.null;

      // Squads config
      expect(policy.squadsMultisig).to.be.null;
      expect(policy.escalationThreshold.toNumber()).to.equal(2_000_000_000);

      // Monitors
      expect(policy.authorizedMonitors).to.have.lengthOf(1);
      expect(policy.authorizedMonitors[0].toBase58()).to.equal(
        monitor1.toBase58()
      );

      // Defaults
      expect(policy.anomalyScore).to.equal(0);

      // --- Verify SpendTracker fields ---
      const tracker = await program.account.spendTracker.fetch(trackerPda);

      expect(tracker.policy.toBase58()).to.equal(policyPda.toBase58());
      // Note: Anchor camelCase converts `_24h` suffix to `24H` (capital H)
      expect((tracker as any).txnCount24H).to.equal(0);
      expect((tracker as any).lamportsSpent24H.toNumber()).to.equal(0);
      expect(tracker.lastTxnTs.toNumber()).to.equal(0);
    });

    it("fails when initializing duplicate policy for same owner+agent", async () => {
      // The first init ran in the previous test — same (owner, agent) PDA exists
      const [policyPda] = findPolicyPda(owner.publicKey, agent.publicKey);
      const [trackerPda] = findTrackerPda(policyPda);

      try {
        await program.methods
          .initializePolicy({
            allowedPrograms: defaultAllowedPrograms,
            maxTxLamports: defaultMaxTxLamports,
            maxTxTokenUnits: defaultMaxTxTokenUnits,
            dailyBudgetLamports: defaultDailyBudgetLamports,
            sessionExpiry: defaultSessionExpiry,
            squadsMultisig: null,
            escalationThreshold: defaultEscalationThreshold,
            authorizedMonitors: [],
          })
          .accounts({
            owner: owner.publicKey,
            agent: agent.publicKey,
            policy: policyPda,
            spendTracker: trackerPda,
            systemProgram: SystemProgram.programId,
          })
          .signers([owner])
          .rpc();

        expect.fail("Expected duplicate init to fail");
      } catch (err: any) {
        // Anchor rejects init on an already-initialized account
        expect(err).to.exist;
      }
    });

    it("fails when allowed_programs exceeds max (10)", async () => {
      const freshAgent = Keypair.generate();
      const [policyPda] = findPolicyPda(owner.publicKey, freshAgent.publicKey);
      const [trackerPda] = findTrackerPda(policyPda);

      // 11 programs exceeds MAX_ALLOWED_PROGRAMS = 10
      const tooManyPrograms = Array.from({ length: 11 }, () =>
        Keypair.generate().publicKey
      );

      try {
        await program.methods
          .initializePolicy({
            allowedPrograms: tooManyPrograms,
            maxTxLamports: defaultMaxTxLamports,
            maxTxTokenUnits: defaultMaxTxTokenUnits,
            dailyBudgetLamports: defaultDailyBudgetLamports,
            sessionExpiry: defaultSessionExpiry,
            squadsMultisig: null,
            escalationThreshold: defaultEscalationThreshold,
            authorizedMonitors: [],
          })
          .accounts({
            owner: owner.publicKey,
            agent: freshAgent.publicKey,
            policy: policyPda,
            spendTracker: trackerPda,
            systemProgram: SystemProgram.programId,
          })
          .signers([owner])
          .rpc();

        expect.fail("Expected TooManyAllowedPrograms error");
      } catch (err: any) {
        expect(err.toString()).to.include("TooManyAllowedPrograms");
      }
    });

    it("fails when max_tx_lamports exceeds daily_budget_lamports", async () => {
      const freshAgent = Keypair.generate();
      const [policyPda] = findPolicyPda(owner.publicKey, freshAgent.publicKey);
      const [trackerPda] = findTrackerPda(policyPda);

      try {
        await program.methods
          .initializePolicy({
            allowedPrograms: defaultAllowedPrograms,
            maxTxLamports: new BN(10_000_000_000), // 10 SOL per tx...
            maxTxTokenUnits: defaultMaxTxTokenUnits,
            dailyBudgetLamports: new BN(5_000_000_000), // ...but only 5 SOL daily
            sessionExpiry: defaultSessionExpiry,
            squadsMultisig: null,
            escalationThreshold: defaultEscalationThreshold,
            authorizedMonitors: [],
          })
          .accounts({
            owner: owner.publicKey,
            agent: freshAgent.publicKey,
            policy: policyPda,
            spendTracker: trackerPda,
            systemProgram: SystemProgram.programId,
          })
          .signers([owner])
          .rpc();

        expect.fail("Expected TxLimitExceedsDailyBudget error");
      } catch (err: any) {
        expect(err.toString()).to.include("TxLimitExceedsDailyBudget");
      }
    });
  });

  // =========================================================================
  // update_policy
  // =========================================================================

  describe("update_policy", () => {
    it("owner can update limits and verify changes", async () => {
      const [policyPda] = findPolicyPda(owner.publicKey, agent.publicKey);

      const newProgram = Keypair.generate().publicKey;
      const newMonitor = Keypair.generate().publicKey;

      await program.methods
        .updatePolicy({
          allowedPrograms: [SystemProgram.programId, newProgram],
          maxTxLamports: new BN(2_000_000_000), // 2 SOL
          maxTxTokenUnits: new BN(2_000_000),
          dailyBudgetLamports: new BN(10_000_000_000), // 10 SOL
          sessionExpiry: null, // unchanged
          squadsMultisig: null, // unchanged
          escalationThreshold: new BN(5_000_000_000), // 5 SOL
          authorizedMonitors: [newMonitor],
          anomalyScore: 42,
        })
        .accounts({
          owner: owner.publicKey,
          policy: policyPda,
        })
        .signers([owner])
        .rpc();

      const policy = await program.account.permissionPolicy.fetch(policyPda);

      // Updated fields
      expect(policy.allowedPrograms).to.have.lengthOf(2);
      expect(policy.allowedPrograms[1].toBase58()).to.equal(
        newProgram.toBase58()
      );
      expect(policy.maxTxLamports.toNumber()).to.equal(2_000_000_000);
      expect(policy.maxTxTokenUnits.toNumber()).to.equal(2_000_000);
      expect(policy.dailyBudgetLamports.toNumber()).to.equal(10_000_000_000);
      expect(policy.escalationThreshold.toNumber()).to.equal(5_000_000_000);
      expect(policy.authorizedMonitors).to.have.lengthOf(1);
      expect(policy.authorizedMonitors[0].toBase58()).to.equal(
        newMonitor.toBase58()
      );
      expect(policy.anomalyScore).to.equal(42);

      // Unchanged fields (passed as null → None → no update)
      expect(policy.sessionExpiry.toNumber()).to.equal(
        defaultSessionExpiry.toNumber()
      );
    });

    it("non-owner cannot update policy", async () => {
      const attacker = Keypair.generate();
      svm.airdrop(attacker.publicKey, 1_000_000_000n); // 1 SOL for fees

      const [policyPda] = findPolicyPda(owner.publicKey, agent.publicKey);

      try {
        await program.methods
          .updatePolicy({
            allowedPrograms: null,
            maxTxLamports: new BN(999_999_999),
            maxTxTokenUnits: null,
            dailyBudgetLamports: null,
            sessionExpiry: null,
            squadsMultisig: null,
            escalationThreshold: null,
            authorizedMonitors: null,
            anomalyScore: null,
          })
          .accounts({
            owner: attacker.publicKey,
            policy: policyPda,
          })
          .signers([attacker])
          .rpc();

        expect.fail("Expected non-owner update to fail");
      } catch (err: any) {
        // has_one constraint rejects because attacker.key != policy.owner
        expect(err).to.exist;
      }
    });

    it("fails when updating allowed_programs above max (10)", async () => {
      const [policyPda] = findPolicyPda(owner.publicKey, agent.publicKey);

      // 11 programs exceeds MAX_ALLOWED_PROGRAMS = 10
      const tooManyPrograms = Array.from({ length: 11 }, () =>
        Keypair.generate().publicKey
      );

      try {
        await program.methods
          .updatePolicy({
            allowedPrograms: tooManyPrograms,
            maxTxLamports: null,
            maxTxTokenUnits: null,
            dailyBudgetLamports: null,
            sessionExpiry: null,
            squadsMultisig: null,
            escalationThreshold: null,
            authorizedMonitors: null,
            anomalyScore: null,
          })
          .accounts({
            owner: owner.publicKey,
            policy: policyPda,
          })
          .signers([owner])
          .rpc();

        expect.fail("Expected TooManyAllowedPrograms error");
      } catch (err: any) {
        expect(err.toString()).to.include("TooManyAllowedPrograms");
      }
    });
  });

  // =========================================================================
  // guarded_execute
  // =========================================================================

  describe("guarded_execute", () => {
    // Fresh keypairs for guarded_execute tests (isolated from update_policy mutations)
    const geOwner = Keypair.generate();
    const geAgent = Keypair.generate();
    const destination = Keypair.generate();

    // Helper: build System Program transfer instruction data
    function buildSystemTransferData(lamports: bigint): Buffer {
      // bytes 0-3: u32 instruction index = 2 (Transfer), little-endian
      // bytes 4-11: u64 lamports, little-endian
      const buf = Buffer.alloc(12);
      buf.writeUInt32LE(2, 0);
      buf.writeBigUInt64LE(lamports, 4);
      return buf;
    }

    let gePolicyPda: PublicKey;
    let geTrackerPda: PublicKey;

    before(async () => {
      // Fund owner and agent
      svm.airdrop(geOwner.publicKey, 10_000_000_000n);
      svm.airdrop(geAgent.publicKey, 5_000_000_000n);

      // Derive PDAs
      [gePolicyPda] = findPolicyPda(geOwner.publicKey, geAgent.publicKey);
      [geTrackerPda] = findTrackerPda(gePolicyPda);

      // Create policy: System Program allowed, 1 SOL per-tx, 5 SOL daily
      await program.methods
        .initializePolicy({
          allowedPrograms: [SystemProgram.programId],
          maxTxLamports: new BN(1_000_000_000), // 1 SOL
          maxTxTokenUnits: new BN(1_000_000),
          dailyBudgetLamports: new BN(5_000_000_000), // 5 SOL
          sessionExpiry: defaultSessionExpiry,
          squadsMultisig: null,
          escalationThreshold: new BN(2_000_000_000), // 2 SOL
          authorizedMonitors: [],
        })
        .accounts({
          owner: geOwner.publicKey,
          agent: geAgent.publicKey,
          policy: gePolicyPda,
          spendTracker: geTrackerPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([geOwner])
        .rpc();

      svm.airdrop(gePolicyPda, 5_000_000_000n); // 5 SOL for rent
    });

    // -----------------------------------------------------------------------
    // Validation rejection tests (steps 2-8 of the 12-step flow)
    // -----------------------------------------------------------------------

    it("rejects when target program is not whitelisted", async () => {
      const fakeProgram = Keypair.generate();
      const instructionData = Buffer.alloc(12);

      try {
        await program.methods
          .guardedExecute({
            instructionData: instructionData,
            amountHint: new BN(100_000),
          })
          .accounts({
            agent: geAgent.publicKey,
            policy: gePolicyPda,
            spendTracker: geTrackerPda,
            targetProgram: fakeProgram.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .remainingAccounts([
            { pubkey: gePolicyPda, isWritable: true, isSigner: false },
            { pubkey: destination.publicKey, isWritable: true, isSigner: false },
            { pubkey: fakeProgram.publicKey, isWritable: false, isSigner: false },
          ])
          .signers([geAgent])
          .rpc();

        expect.fail("Expected ProgramNotWhitelisted error");
      } catch (err: any) {
        expect(err.toString()).to.include("ProgramNotWhitelisted");
      }
    });

    it("rejects when amount exceeds per-tx limit", async () => {
      const tooBig = 2_000_000_000n; // 2 SOL > 1 SOL max
      const instructionData = buildSystemTransferData(tooBig);

      try {
        await program.methods
          .guardedExecute({
            instructionData: instructionData,
            amountHint: new BN(Number(tooBig)),
          })
          .accounts({
            agent: geAgent.publicKey,
            policy: gePolicyPda,
            spendTracker: geTrackerPda,
            targetProgram: SystemProgram.programId,
            systemProgram: SystemProgram.programId,
          })
          .remainingAccounts([
            { pubkey: gePolicyPda, isWritable: true, isSigner: false },
            { pubkey: destination.publicKey, isWritable: true, isSigner: false },
            { pubkey: SystemProgram.programId, isWritable: false, isSigner: false },
          ])
          .signers([geAgent])
          .rpc();

        expect.fail("Expected AmountExceedsLimit error");
      } catch (err: any) {
        expect(err.toString()).to.include("AmountExceedsLimit");
      }
    });

    it("rejects when amount_hint mismatches parsed System Program data", async () => {
      // amount_hint says 50k but instruction data says 200k → AmountMismatch
      const realAmount = 200_000n;
      const instructionData = buildSystemTransferData(realAmount);

      try {
        await program.methods
          .guardedExecute({
            instructionData: instructionData,
            amountHint: new BN(50_000), // Lies about the amount
          })
          .accounts({
            agent: geAgent.publicKey,
            policy: gePolicyPda,
            spendTracker: geTrackerPda,
            targetProgram: SystemProgram.programId,
            systemProgram: SystemProgram.programId,
          })
          .remainingAccounts([
            { pubkey: gePolicyPda, isWritable: true, isSigner: false },
            { pubkey: destination.publicKey, isWritable: true, isSigner: false },
            { pubkey: SystemProgram.programId, isWritable: false, isSigner: false },
          ])
          .signers([geAgent])
          .rpc();

        expect.fail("Expected AmountMismatch error");
      } catch (err: any) {
        expect(err.toString()).to.include("AmountMismatch");
      }
    });

    // NOTE: DailyBudgetExceeded requires cumulative spending from prior
    // successful CPIs. Tested when Token Program CPI is integrated.

    it("rejects when session has expired", async () => {
      // Create a policy with a session_expiry just 10 seconds from 'now'
      const expiryAgent = Keypair.generate();
      svm.airdrop(expiryAgent.publicKey, 2_000_000_000n);

      // Get current clock timestamp from LiteSVM
      const currentClock = svm.getClock();
      const shortExpiry = new BN(Number(currentClock.unixTimestamp) + 10);

      const [ePolicyPda] = findPolicyPda(geOwner.publicKey, expiryAgent.publicKey);
      const [eTrackerPda] = findTrackerPda(ePolicyPda);

      await program.methods
        .initializePolicy({
          allowedPrograms: [SystemProgram.programId],
          maxTxLamports: new BN(1_000_000_000),
          maxTxTokenUnits: new BN(1_000_000),
          dailyBudgetLamports: new BN(5_000_000_000),
          sessionExpiry: shortExpiry,
          squadsMultisig: null,
          escalationThreshold: new BN(10_000_000_000),
          authorizedMonitors: [],
        })
        .accounts({
          owner: geOwner.publicKey,
          agent: expiryAgent.publicKey,
          policy: ePolicyPda,
          spendTracker: eTrackerPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([geOwner])
        .rpc();

      svm.airdrop(ePolicyPda, 2_000_000_000n);

      // Warp clock past session_expiry using Clock constructor
      svm.setClock(new Clock(
        currentClock.slot + 100n,
        currentClock.epochStartTimestamp,
        currentClock.epoch,
        currentClock.leaderScheduleEpoch,
        BigInt(shortExpiry.toNumber() + 100),
      ));

      const txData = buildSystemTransferData(100_000n);
      try {
        await program.methods
          .guardedExecute({
            instructionData: txData,
            amountHint: new BN(100_000),
          })
          .accounts({
            agent: expiryAgent.publicKey,
            policy: ePolicyPda,
            spendTracker: eTrackerPda,
            targetProgram: SystemProgram.programId,
            systemProgram: SystemProgram.programId,
          })
          .remainingAccounts([
            { pubkey: ePolicyPda, isWritable: true, isSigner: false },
            { pubkey: destination.publicKey, isWritable: true, isSigner: false },
            { pubkey: SystemProgram.programId, isWritable: false, isSigner: false },
          ])
          .signers([expiryAgent])
          .rpc();

        expect.fail("Expected SessionExpired error");
      } catch (err: any) {
        expect(err.toString()).to.include("SessionExpired");
      }

      // Reset clock for subsequent tests
      svm.setClock(currentClock);
    });

    it("rejects with EscalatedToMultisig when amount > threshold and squads set", async () => {
      // Create a policy with squads_multisig set and low escalation threshold
      const escAgent = Keypair.generate();
      svm.airdrop(escAgent.publicKey, 2_000_000_000n);

      const squadsMultisig = Keypair.generate().publicKey;

      const [escPolicyPda] = findPolicyPda(geOwner.publicKey, escAgent.publicKey);
      const [escTrackerPda] = findTrackerPda(escPolicyPda);

      await program.methods
        .initializePolicy({
          allowedPrograms: [SystemProgram.programId],
          maxTxLamports: new BN(2_000_000_000), // 2 SOL
          maxTxTokenUnits: new BN(1_000_000),
          dailyBudgetLamports: new BN(10_000_000_000), // 10 SOL
          sessionExpiry: defaultSessionExpiry,
          squadsMultisig: squadsMultisig,
          escalationThreshold: new BN(500_000_000), // 0.5 SOL
          authorizedMonitors: [],
        })
        .accounts({
          owner: geOwner.publicKey,
          agent: escAgent.publicKey,
          policy: escPolicyPda,
          spendTracker: escTrackerPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([geOwner])
        .rpc();

      svm.airdrop(escPolicyPda, 5_000_000_000n);

      // Try 1 SOL transfer (> 0.5 SOL threshold) → should escalate
      const txData = buildSystemTransferData(1_000_000_000n);
      try {
        await program.methods
          .guardedExecute({
            instructionData: txData,
            amountHint: new BN(1_000_000_000),
          })
          .accounts({
            agent: escAgent.publicKey,
            policy: escPolicyPda,
            spendTracker: escTrackerPda,
            targetProgram: SystemProgram.programId,
            systemProgram: SystemProgram.programId,
          })
          .remainingAccounts([
            { pubkey: escPolicyPda, isWritable: true, isSigner: false },
            { pubkey: destination.publicKey, isWritable: true, isSigner: false },
            { pubkey: SystemProgram.programId, isWritable: false, isSigner: false },
          ])
          .signers([escAgent])
          .rpc();

        expect.fail("Expected EscalatedToMultisig error");
      } catch (err: any) {
        expect(err.toString()).to.include("EscalatedToMultisig");
      }
    });

    // -----------------------------------------------------------------------
    // Token Program CPI tests (happy path + budget enforcement)
    // -----------------------------------------------------------------------

    describe("token program CPI", () => {
      const tOwner = Keypair.generate();
      const tAgent = Keypair.generate();
      const mintAuthority = Keypair.generate();
      const mintKeypair = Keypair.generate();
      const sourceTokenKeypair = Keypair.generate();
      const destTokenKeypair = Keypair.generate();

      let tPolicyPda: PublicKey;
      let tTrackerPda: PublicKey;

      // Transfer 300k per tx. Policy: max_tx=500k, daily=800k.
      // Narrative: tx1(300k ok) → tx2(600k ok) → tx3(900k>800k rejected) → warp 24h → tx4(300k ok)
      const TRANSFER_AMOUNT = 300_000n;

      before(async () => {
        svm.airdrop(tOwner.publicKey, 10_000_000_000n);
        svm.airdrop(tAgent.publicKey, 5_000_000_000n);
        svm.airdrop(mintAuthority.publicKey, 5_000_000_000n);

        [tPolicyPda] = findPolicyPda(tOwner.publicKey, tAgent.publicKey);
        [tTrackerPda] = findTrackerPda(tPolicyPda);

        // Create policy with Token Program whitelisted
        await program.methods
          .initializePolicy({
            allowedPrograms: [TOKEN_PROGRAM_ID],
            maxTxLamports: new BN(500_000),
            maxTxTokenUnits: new BN(1_000_000),
            dailyBudgetLamports: new BN(800_000),
            sessionExpiry: defaultSessionExpiry,
            squadsMultisig: null,
            escalationThreshold: new BN(10_000_000_000),
            authorizedMonitors: [],
          })
          .accounts({
            owner: tOwner.publicKey,
            agent: tAgent.publicKey,
            policy: tPolicyPda,
            spendTracker: tTrackerPda,
            systemProgram: SystemProgram.programId,
          })
          .signers([tOwner])
          .rpc();

        // Create mint
        await createTestMint(mintKeypair, mintAuthority.publicKey, 6);

        // Create source token account: authority = policy PDA
        await createTestTokenAccount(sourceTokenKeypair, mintKeypair.publicKey, tPolicyPda);

        // Create destination token account
        await createTestTokenAccount(
          destTokenKeypair,
          mintKeypair.publicKey,
          Keypair.generate().publicKey,
        );

        // Mint tokens into source
        await mintTestTokens(
          mintKeypair.publicKey,
          sourceTokenKeypair.publicKey,
          mintAuthority,
          5_000_000n,
        );
      });

      it("transfers tokens via guarded_execute and verifies balances", async () => {
        const instructionData = buildTokenTransferData(TRANSFER_AMOUNT);
        const srcBefore = getTokenBalance(sourceTokenKeypair.publicKey);
        const dstBefore = getTokenBalance(destTokenKeypair.publicKey);

        await program.methods
          .guardedExecute({
            instructionData: instructionData,
            amountHint: new BN(Number(TRANSFER_AMOUNT)),
          })
          .accounts({
            agent: tAgent.publicKey,
            policy: tPolicyPda,
            spendTracker: tTrackerPda,
            targetProgram: TOKEN_PROGRAM_ID,
            systemProgram: SystemProgram.programId,
          })
          .remainingAccounts([
            { pubkey: sourceTokenKeypair.publicKey, isWritable: true, isSigner: false },
            { pubkey: destTokenKeypair.publicKey, isWritable: true, isSigner: false },
            { pubkey: tPolicyPda, isWritable: false, isSigner: false },
            { pubkey: TOKEN_PROGRAM_ID, isWritable: false, isSigner: false },
          ])
          .signers([tAgent])
          .rpc();

        // Verify token balances changed
        expect(getTokenBalance(sourceTokenKeypair.publicKey)).to.equal(srcBefore - TRANSFER_AMOUNT);
        expect(getTokenBalance(destTokenKeypair.publicKey)).to.equal(dstBefore + TRANSFER_AMOUNT);
      });

      it("updates SpendTracker and policy counters after successful transfer", async () => {
        const tracker = await program.account.spendTracker.fetch(tTrackerPda);
        expect((tracker as any).txnCount24H).to.equal(1);
        expect((tracker as any).lamportsSpent24H.toNumber()).to.equal(Number(TRANSFER_AMOUNT));
        expect(tracker.lastTxnProgram.toBase58()).to.equal(TOKEN_PROGRAM_ID.toBase58());

        const policy = await program.account.permissionPolicy.fetch(tPolicyPda);
        expect(policy.dailySpentLamports.toNumber()).to.equal(Number(TRANSFER_AMOUNT));
      });

      it("rejects third transfer that would exceed daily budget", async () => {
        // Second transfer: 200k → cumulative = 500k < 800k daily budget → succeeds
        // (Use different amount than first transfer to avoid LiteSVM tx dedup)
        const secondAmount = 200_000n;
        await program.methods
          .guardedExecute({
            instructionData: buildTokenTransferData(secondAmount),
            amountHint: new BN(Number(secondAmount)),
          })
          .accounts({
            agent: tAgent.publicKey,
            policy: tPolicyPda,
            spendTracker: tTrackerPda,
            targetProgram: TOKEN_PROGRAM_ID,
            systemProgram: SystemProgram.programId,
          })
          .remainingAccounts([
            { pubkey: sourceTokenKeypair.publicKey, isWritable: true, isSigner: false },
            { pubkey: destTokenKeypair.publicKey, isWritable: true, isSigner: false },
            { pubkey: tPolicyPda, isWritable: false, isSigner: false },
            { pubkey: TOKEN_PROGRAM_ID, isWritable: false, isSigner: false },
          ])
          .signers([tAgent])
          .rpc();

        // Verify cumulative = 500k (300k + 200k) after 2 transfers
        const tracker = await program.account.spendTracker.fetch(tTrackerPda);
        expect((tracker as any).txnCount24H).to.equal(2);
        expect((tracker as any).lamportsSpent24H.toNumber()).to.equal(500_000);

        // Third transfer of 400k: cumulative would be 900k > 800k → DailyBudgetExceeded
        const thirdAmount = 400_000n;
        try {
          await program.methods
            .guardedExecute({
              instructionData: buildTokenTransferData(thirdAmount),
              amountHint: new BN(Number(thirdAmount)),
            })
            .accounts({
              agent: tAgent.publicKey,
              policy: tPolicyPda,
              spendTracker: tTrackerPda,
              targetProgram: TOKEN_PROGRAM_ID,
              systemProgram: SystemProgram.programId,
            })
            .remainingAccounts([
              { pubkey: sourceTokenKeypair.publicKey, isWritable: true, isSigner: false },
              { pubkey: destTokenKeypair.publicKey, isWritable: true, isSigner: false },
              { pubkey: tPolicyPda, isWritable: false, isSigner: false },
              { pubkey: TOKEN_PROGRAM_ID, isWritable: false, isSigner: false },
            ])
            .signers([tAgent])
            .rpc();

          expect.fail("Expected DailyBudgetExceeded error");
        } catch (err: any) {
          expect(err.toString()).to.include("DailyBudgetExceeded");
        }
      });

      it("allows spending again after 24h budget window rollover", async () => {
        // Current state: daily_spent = 500k, daily_budget = 800k
        // Warp clock 25 hours → budget resets to 0 → 250k should succeed
        const rolloverAmount = 250_000n; // Unique amount to avoid tx dedup
        const currentClock = svm.getClock();
        try {
          svm.setClock(new Clock(
            currentClock.slot + 1000n,
            currentClock.epochStartTimestamp,
            currentClock.epoch,
            currentClock.leaderScheduleEpoch,
            currentClock.unixTimestamp + 90_000n, // +25 hours
          ));

          const srcBefore = getTokenBalance(sourceTokenKeypair.publicKey);

          await program.methods
            .guardedExecute({
              instructionData: buildTokenTransferData(rolloverAmount),
              amountHint: new BN(Number(rolloverAmount)),
            })
            .accounts({
              agent: tAgent.publicKey,
              policy: tPolicyPda,
              spendTracker: tTrackerPda,
              targetProgram: TOKEN_PROGRAM_ID,
              systemProgram: SystemProgram.programId,
            })
            .remainingAccounts([
              { pubkey: sourceTokenKeypair.publicKey, isWritable: true, isSigner: false },
              { pubkey: destTokenKeypair.publicKey, isWritable: true, isSigner: false },
              { pubkey: tPolicyPda, isWritable: false, isSigner: false },
              { pubkey: TOKEN_PROGRAM_ID, isWritable: false, isSigner: false },
            ])
            .signers([tAgent])
            .rpc();

          // Verify transfer went through
          expect(getTokenBalance(sourceTokenKeypair.publicKey)).to.equal(
            srcBefore - rolloverAmount
          );

          // Verify counters reset — only this transfer in the new window
          const tracker = await program.account.spendTracker.fetch(tTrackerPda);
          expect((tracker as any).txnCount24H).to.equal(1);
          expect((tracker as any).lamportsSpent24H.toNumber()).to.equal(Number(rolloverAmount));

          const policy = await program.account.permissionPolicy.fetch(tPolicyPda);
          expect(policy.dailySpentLamports.toNumber()).to.equal(Number(rolloverAmount));
        } finally {
          svm.setClock(currentClock);
        }
      });

      it("rejects when amount_hint mismatches Token Program instruction data", async () => {
        const realAmount = 200_000n;
        const instructionData = buildTokenTransferData(realAmount);

        try {
          await program.methods
            .guardedExecute({
              instructionData: instructionData,
              amountHint: new BN(50_000), // Lies about the amount
            })
            .accounts({
              agent: tAgent.publicKey,
              policy: tPolicyPda,
              spendTracker: tTrackerPda,
              targetProgram: TOKEN_PROGRAM_ID,
              systemProgram: SystemProgram.programId,
            })
            .remainingAccounts([
              { pubkey: sourceTokenKeypair.publicKey, isWritable: true, isSigner: false },
              { pubkey: destTokenKeypair.publicKey, isWritable: true, isSigner: false },
              { pubkey: tPolicyPda, isWritable: false, isSigner: false },
              { pubkey: TOKEN_PROGRAM_ID, isWritable: false, isSigner: false },
            ])
            .signers([tAgent])
            .rpc();

          expect.fail("Expected AmountMismatch error");
        } catch (err: any) {
          expect(err.toString()).to.include("AmountMismatch");
        }
      });
    });
  });

  // =========================================================================
  // pause_agent
  // =========================================================================

  describe("pause_agent", () => {
    const pauseOwner = Keypair.generate();
    const pauseAgent = Keypair.generate();
    const monitor = Keypair.generate();
    let pausePolicyPda: PublicKey;
    let pauseTrackerPda: PublicKey;

    before(async () => {
      svm.airdrop(pauseOwner.publicKey, 10_000_000_000n);
      svm.airdrop(monitor.publicKey, 1_000_000_000n);
      svm.airdrop(pauseAgent.publicKey, 2_000_000_000n);

      [pausePolicyPda] = findPolicyPda(pauseOwner.publicKey, pauseAgent.publicKey);
      [pauseTrackerPda] = findTrackerPda(pausePolicyPda);

      // Create policy with monitor authorized
      await program.methods
        .initializePolicy({
          allowedPrograms: [SystemProgram.programId],
          maxTxLamports: new BN(1_000_000_000),
          maxTxTokenUnits: new BN(1_000_000),
          dailyBudgetLamports: new BN(5_000_000_000),
          sessionExpiry: defaultSessionExpiry,
          squadsMultisig: null,
          escalationThreshold: new BN(2_000_000_000),
          authorizedMonitors: [monitor.publicKey],
        })
        .accounts({
          owner: pauseOwner.publicKey,
          agent: pauseAgent.publicKey,
          policy: pausePolicyPda,
          spendTracker: pauseTrackerPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([pauseOwner])
        .rpc();
    });

    it("owner can pause agent with reason", async () => {
      const reason = Buffer.from("Suspicious activity detected");

      await program.methods
        .pauseAgent({ reason: reason })
        .accounts({
          caller: pauseOwner.publicKey,
          policy: pausePolicyPda,
        })
        .signers([pauseOwner])
        .rpc();

      const policy = await program.account.permissionPolicy.fetch(pausePolicyPda);
      expect(policy.isActive).to.be.false;
      expect(policy.pausedBy.toBase58()).to.equal(pauseOwner.publicKey.toBase58());

      // Verify reason bytes match
      const storedReason = Buffer.from(policy.pausedReason);
      expect(storedReason.subarray(0, reason.length).toString()).to.equal(
        reason.toString()
      );
    });

    it("owner resumes so monitor can pause next", async () => {
      await program.methods
        .resumeAgent()
        .accounts({
          owner: pauseOwner.publicKey,
          policy: pausePolicyPda,
        })
        .signers([pauseOwner])
        .rpc();

      const policy = await program.account.permissionPolicy.fetch(pausePolicyPda);
      expect(policy.isActive).to.be.true;
    });

    it("authorized monitor can pause agent", async () => {
      await program.methods
        .pauseAgent({ reason: Buffer.from("Anomaly score exceeded") })
        .accounts({
          caller: monitor.publicKey,
          policy: pausePolicyPda,
        })
        .signers([monitor])
        .rpc();

      const policy = await program.account.permissionPolicy.fetch(pausePolicyPda);
      expect(policy.isActive).to.be.false;
      expect(policy.pausedBy.toBase58()).to.equal(monitor.publicKey.toBase58());
    });

    it("unauthorized caller cannot pause agent", async () => {
      // Use a fresh policy to avoid state dependencies on previous tests
      const freshOwner = Keypair.generate();
      const freshAgent = Keypair.generate();
      svm.airdrop(freshOwner.publicKey, 10_000_000_000n);

      const [freshPolicyPda] = findPolicyPda(freshOwner.publicKey, freshAgent.publicKey);
      const [freshTrackerPda] = findTrackerPda(freshPolicyPda);

      await program.methods
        .initializePolicy({
          allowedPrograms: [SystemProgram.programId],
          maxTxLamports: new BN(1_000_000_000),
          maxTxTokenUnits: new BN(1_000_000),
          dailyBudgetLamports: new BN(5_000_000_000),
          sessionExpiry: defaultSessionExpiry,
          squadsMultisig: null,
          escalationThreshold: new BN(2_000_000_000),
          authorizedMonitors: [], // No monitors — only owner can pause
        })
        .accounts({
          owner: freshOwner.publicKey,
          agent: freshAgent.publicKey,
          policy: freshPolicyPda,
          spendTracker: freshTrackerPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([freshOwner])
        .rpc();

      const attacker = Keypair.generate();
      svm.airdrop(attacker.publicKey, 1_000_000_000n);

      try {
        await program.methods
          .pauseAgent({ reason: Buffer.from("hacked") })
          .accounts({ caller: attacker.publicKey, policy: freshPolicyPda })
          .signers([attacker])
          .rpc();

        expect.fail("Expected UnauthorizedPauser error");
      } catch (err: any) {
        // Attacker is neither owner nor monitor — transaction must fail
        expect(err).to.exist;
      }
    });

    it("paused policy rejects guarded_execute with PolicyPaused", async () => {
      // Pause the policy
      await program.methods
        .pauseAgent({ reason: Buffer.from("Kill switch test") })
        .accounts({ caller: pauseOwner.publicKey, policy: pausePolicyPda })
        .signers([pauseOwner])
        .rpc();

      // Try guarded_execute — should fail with PolicyPaused
      const dest = Keypair.generate();
      const txData = Buffer.alloc(12);
      txData.writeUInt32LE(2, 0);
      txData.writeBigUInt64LE(100_000n, 4);

      try {
        await program.methods
          .guardedExecute({
            instructionData: txData,
            amountHint: new BN(100_000),
          })
          .accounts({
            agent: pauseAgent.publicKey,
            policy: pausePolicyPda,
            spendTracker: pauseTrackerPda,
            targetProgram: SystemProgram.programId,
            systemProgram: SystemProgram.programId,
          })
          .remainingAccounts([
            { pubkey: pausePolicyPda, isWritable: true, isSigner: false },
            { pubkey: dest.publicKey, isWritable: true, isSigner: false },
            { pubkey: SystemProgram.programId, isWritable: false, isSigner: false },
          ])
          .signers([pauseAgent])
          .rpc();

        expect.fail("Expected PolicyPaused error");
      } catch (err: any) {
        expect(err.toString()).to.include("PolicyPaused");
      }
    });
  });

  // =========================================================================
  // resume_agent
  // =========================================================================

  describe("resume_agent", () => {
    const resumeOwner = Keypair.generate();
    const resumeAgent = Keypair.generate();
    const resumeMonitor = Keypair.generate();
    let resumePolicyPda: PublicKey;

    before(async () => {
      svm.airdrop(resumeOwner.publicKey, 10_000_000_000n);
      svm.airdrop(resumeMonitor.publicKey, 1_000_000_000n);

      [resumePolicyPda] = findPolicyPda(resumeOwner.publicKey, resumeAgent.publicKey);
      const [resumeTrackerPda] = findTrackerPda(resumePolicyPda);

      // Create policy and immediately pause it
      await program.methods
        .initializePolicy({
          allowedPrograms: [SystemProgram.programId],
          maxTxLamports: new BN(1_000_000_000),
          maxTxTokenUnits: new BN(1_000_000),
          dailyBudgetLamports: new BN(5_000_000_000),
          sessionExpiry: defaultSessionExpiry,
          squadsMultisig: null,
          escalationThreshold: new BN(2_000_000_000),
          authorizedMonitors: [resumeMonitor.publicKey],
        })
        .accounts({
          owner: resumeOwner.publicKey,
          agent: resumeAgent.publicKey,
          policy: resumePolicyPda,
          spendTracker: resumeTrackerPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([resumeOwner])
        .rpc();

      // Pause it for resume tests
      await program.methods
        .pauseAgent({ reason: Buffer.from("Paused for resume tests") })
        .accounts({ caller: resumeOwner.publicKey, policy: resumePolicyPda })
        .signers([resumeOwner])
        .rpc();
    });

    it("owner can resume a paused agent", async () => {
      await program.methods
        .resumeAgent()
        .accounts({ owner: resumeOwner.publicKey, policy: resumePolicyPda })
        .signers([resumeOwner])
        .rpc();

      const policy = await program.account.permissionPolicy.fetch(resumePolicyPda);
      expect(policy.isActive).to.be.true;
      expect(policy.pausedBy).to.be.null;

      // Verify paused_reason is cleared (all zeros)
      const storedReason = Buffer.from(policy.pausedReason);
      expect(storedReason.every((b: number) => b === 0)).to.be.true;
    });

    it("monitor cannot resume a paused agent", async () => {
      // Re-pause for this test
      await program.methods
        .pauseAgent({ reason: Buffer.from("Re-paused") })
        .accounts({ caller: resumeOwner.publicKey, policy: resumePolicyPda })
        .signers([resumeOwner])
        .rpc();

      try {
        await program.methods
          .resumeAgent()
          .accounts({ owner: resumeMonitor.publicKey, policy: resumePolicyPda })
          .signers([resumeMonitor])
          .rpc();

        expect.fail("Expected ResumeRequiresOwner error");
      } catch (err: any) {
        expect(err).to.exist;
      }
    });

    it("random caller cannot resume a paused agent", async () => {
      const attacker = Keypair.generate();
      svm.airdrop(attacker.publicKey, 1_000_000_000n);

      try {
        await program.methods
          .resumeAgent()
          .accounts({ owner: attacker.publicKey, policy: resumePolicyPda })
          .signers([attacker])
          .rpc();

        expect.fail("Expected resume to fail for non-owner");
      } catch (err: any) {
        expect(err).to.exist;
      }
    });
  });

  // =========================================================================
  // Integration tests — cross-instruction lifecycle flows
  // =========================================================================

  describe("integration", () => {
    it("full lifecycle: init → pause → execute rejected → resume → execute passes validation", async () => {
      const iOwner = Keypair.generate();
      const iAgent = Keypair.generate();
      svm.airdrop(iOwner.publicKey, 10_000_000_000n);
      svm.airdrop(iAgent.publicKey, 2_000_000_000n);

      const [iPolicyPda] = findPolicyPda(iOwner.publicKey, iAgent.publicKey);
      const [iTrackerPda] = findTrackerPda(iPolicyPda);

      // Step 1: Initialize policy
      await program.methods
        .initializePolicy({
          allowedPrograms: [SystemProgram.programId],
          maxTxLamports: new BN(1_000_000_000),
          maxTxTokenUnits: new BN(1_000_000),
          dailyBudgetLamports: new BN(5_000_000_000),
          sessionExpiry: defaultSessionExpiry,
          squadsMultisig: null,
          escalationThreshold: new BN(2_000_000_000),
          authorizedMonitors: [],
        })
        .accounts({
          owner: iOwner.publicKey,
          agent: iAgent.publicKey,
          policy: iPolicyPda,
          spendTracker: iTrackerPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([iOwner])
        .rpc();

      // Step 2: Pause the agent
      await program.methods
        .pauseAgent({ reason: Buffer.from("Anomaly detected") })
        .accounts({ caller: iOwner.publicKey, policy: iPolicyPda })
        .signers([iOwner])
        .rpc();

      // Step 3: guarded_execute should fail with PolicyPaused
      const dest = Keypair.generate();
      const txData = Buffer.alloc(12);
      txData.writeUInt32LE(2, 0);
      txData.writeBigUInt64LE(100_000n, 4);

      try {
        await program.methods
          .guardedExecute({ instructionData: txData, amountHint: new BN(100_000) })
          .accounts({
            agent: iAgent.publicKey,
            policy: iPolicyPda,
            spendTracker: iTrackerPda,
            targetProgram: SystemProgram.programId,
            systemProgram: SystemProgram.programId,
          })
          .remainingAccounts([
            { pubkey: iPolicyPda, isWritable: true, isSigner: false },
            { pubkey: dest.publicKey, isWritable: true, isSigner: false },
            { pubkey: SystemProgram.programId, isWritable: false, isSigner: false },
          ])
          .signers([iAgent])
          .rpc();
        expect.fail("Expected PolicyPaused");
      } catch (err: any) {
        expect(err.toString()).to.include("PolicyPaused");
      }

      // Step 4: Resume the agent
      await program.methods
        .resumeAgent()
        .accounts({ owner: iOwner.publicKey, policy: iPolicyPda })
        .signers([iOwner])
        .rpc();

      // Step 5: guarded_execute should now pass validation (will fail at CPI
      // stage because policy PDA can't do System Program transfers, but the
      // error should NOT be PolicyPaused — proving the resume worked)
      try {
        await program.methods
          .guardedExecute({ instructionData: txData, amountHint: new BN(100_000) })
          .accounts({
            agent: iAgent.publicKey,
            policy: iPolicyPda,
            spendTracker: iTrackerPda,
            targetProgram: SystemProgram.programId,
            systemProgram: SystemProgram.programId,
          })
          .remainingAccounts([
            { pubkey: iPolicyPda, isWritable: true, isSigner: false },
            { pubkey: dest.publicKey, isWritable: true, isSigner: false },
            { pubkey: SystemProgram.programId, isWritable: false, isSigner: false },
          ])
          .signers([iAgent])
          .rpc();
      } catch (err: any) {
        // Should fail at CPI (not PolicyPaused) — validation passed
        expect(err.toString()).to.not.include("PolicyPaused");
      }
    });

    it("policy update enforces new limits on guarded_execute", async () => {
      const uOwner = Keypair.generate();
      const uAgent = Keypair.generate();
      svm.airdrop(uOwner.publicKey, 10_000_000_000n);
      svm.airdrop(uAgent.publicKey, 2_000_000_000n);

      const [uPolicyPda] = findPolicyPda(uOwner.publicKey, uAgent.publicKey);
      const [uTrackerPda] = findTrackerPda(uPolicyPda);

      // Init with 1 SOL per-tx limit
      await program.methods
        .initializePolicy({
          allowedPrograms: [SystemProgram.programId],
          maxTxLamports: new BN(1_000_000_000),
          maxTxTokenUnits: new BN(1_000_000),
          dailyBudgetLamports: new BN(5_000_000_000),
          sessionExpiry: defaultSessionExpiry,
          squadsMultisig: null,
          escalationThreshold: new BN(10_000_000_000),
          authorizedMonitors: [],
        })
        .accounts({
          owner: uOwner.publicKey,
          agent: uAgent.publicKey,
          policy: uPolicyPda,
          spendTracker: uTrackerPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([uOwner])
        .rpc();

      // Update: lower per-tx limit to 100k lamports
      await program.methods
        .updatePolicy({
          allowedPrograms: null,
          maxTxLamports: new BN(100_000),
          maxTxTokenUnits: null,
          dailyBudgetLamports: null,
          sessionExpiry: null,
          squadsMultisig: null,
          escalationThreshold: null,
          authorizedMonitors: null,
          anomalyScore: null,
        })
        .accounts({ owner: uOwner.publicKey, policy: uPolicyPda })
        .signers([uOwner])
        .rpc();

      // Try 200k lamports — should now fail with AmountExceedsLimit (new limit enforced)
      const txData = Buffer.alloc(12);
      txData.writeUInt32LE(2, 0);
      txData.writeBigUInt64LE(200_000n, 4);

      try {
        await program.methods
          .guardedExecute({ instructionData: txData, amountHint: new BN(200_000) })
          .accounts({
            agent: uAgent.publicKey,
            policy: uPolicyPda,
            spendTracker: uTrackerPda,
            targetProgram: SystemProgram.programId,
            systemProgram: SystemProgram.programId,
          })
          .remainingAccounts([
            { pubkey: uPolicyPda, isWritable: true, isSigner: false },
            { pubkey: Keypair.generate().publicKey, isWritable: true, isSigner: false },
            { pubkey: SystemProgram.programId, isWritable: false, isSigner: false },
          ])
          .signers([uAgent])
          .rpc();
        expect.fail("Expected AmountExceedsLimit");
      } catch (err: any) {
        expect(err.toString()).to.include("AmountExceedsLimit");
      }
    });

    it("budget window resets after 24h via setClock", async () => {
      const bOwner = Keypair.generate();
      const bAgent = Keypair.generate();
      svm.airdrop(bOwner.publicKey, 10_000_000_000n);
      svm.airdrop(bAgent.publicKey, 2_000_000_000n);

      const [bPolicyPda] = findPolicyPda(bOwner.publicKey, bAgent.publicKey);
      const [bTrackerPda] = findTrackerPda(bPolicyPda);

      // Create policy: per-tx = daily = 500k lamports (tight budget)
      await program.methods
        .initializePolicy({
          allowedPrograms: [SystemProgram.programId],
          maxTxLamports: new BN(500_000),
          maxTxTokenUnits: new BN(1_000_000),
          dailyBudgetLamports: new BN(500_000),
          sessionExpiry: defaultSessionExpiry,
          squadsMultisig: null,
          escalationThreshold: new BN(10_000_000_000),
          authorizedMonitors: [],
        })
        .accounts({
          owner: bOwner.publicKey,
          agent: bAgent.publicKey,
          policy: bPolicyPda,
          spendTracker: bTrackerPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([bOwner])
        .rpc();

      const currentClock = svm.getClock();

      // Verify: BEFORE clock warp, a 500k transfer passes validation (per-tx
      // and daily budget checks both pass since daily_spent starts at 0).
      // It will fail at CPI, but NOT with a budget error.
      const txData = Buffer.alloc(12);
      txData.writeUInt32LE(2, 0);
      txData.writeBigUInt64LE(500_000n, 4);

      try {
        await program.methods
          .guardedExecute({ instructionData: txData, amountHint: new BN(500_000) })
          .accounts({
            agent: bAgent.publicKey,
            policy: bPolicyPda,
            spendTracker: bTrackerPda,
            targetProgram: SystemProgram.programId,
            systemProgram: SystemProgram.programId,
          })
          .remainingAccounts([
            { pubkey: bPolicyPda, isWritable: true, isSigner: false },
            { pubkey: Keypair.generate().publicKey, isWritable: true, isSigner: false },
            { pubkey: SystemProgram.programId, isWritable: false, isSigner: false },
          ])
          .signers([bAgent])
          .rpc();
      } catch (err: any) {
        // CPI fails (policy PDA has data), but validation passed — no budget error
        expect(err.toString()).to.not.include("DailyBudgetExceeded");
        expect(err.toString()).to.not.include("AmountExceedsLimit");
      }

      // Warp clock past 24h boundary, then verify the same transfer still
      // passes validation (budget window resets in guarded_execute step 6).
      // NOTE: Since CPI fails and the transaction rolls back, the budget
      // counters are never actually persisted. This test verifies the reset
      // code path executes without error, not cumulative budget exhaustion
      // (which requires successful CPI via Token Program — deferred).
      try {
        svm.setClock(new Clock(
          currentClock.slot + 1000n,
          currentClock.epochStartTimestamp,
          currentClock.epoch,
          currentClock.leaderScheduleEpoch,
          currentClock.unixTimestamp + 90_000n, // +25 hours
        ));

        await program.methods
          .guardedExecute({ instructionData: txData, amountHint: new BN(500_000) })
          .accounts({
            agent: bAgent.publicKey,
            policy: bPolicyPda,
            spendTracker: bTrackerPda,
            targetProgram: SystemProgram.programId,
            systemProgram: SystemProgram.programId,
          })
          .remainingAccounts([
            { pubkey: bPolicyPda, isWritable: true, isSigner: false },
            { pubkey: Keypair.generate().publicKey, isWritable: true, isSigner: false },
            { pubkey: SystemProgram.programId, isWritable: false, isSigner: false },
          ])
          .signers([bAgent])
          .rpc();
      } catch (err: any) {
        // After clock warp: should still NOT fail with budget errors
        expect(err.toString()).to.not.include("DailyBudgetExceeded");
        expect(err.toString()).to.not.include("AmountExceedsLimit");
      } finally {
        // Always restore clock for subsequent tests
        svm.setClock(currentClock);
      }
    });

    it("monitor can pause but cannot resume — owner must resume", async () => {
      const mOwner = Keypair.generate();
      const mAgent = Keypair.generate();
      const mMonitor = Keypair.generate();
      svm.airdrop(mOwner.publicKey, 10_000_000_000n);
      svm.airdrop(mMonitor.publicKey, 1_000_000_000n);

      const [mPolicyPda] = findPolicyPda(mOwner.publicKey, mAgent.publicKey);
      const [mTrackerPda] = findTrackerPda(mPolicyPda);

      // Create policy with monitor authorized
      await program.methods
        .initializePolicy({
          allowedPrograms: [SystemProgram.programId],
          maxTxLamports: new BN(1_000_000_000),
          maxTxTokenUnits: new BN(1_000_000),
          dailyBudgetLamports: new BN(5_000_000_000),
          sessionExpiry: defaultSessionExpiry,
          squadsMultisig: null,
          escalationThreshold: new BN(2_000_000_000),
          authorizedMonitors: [mMonitor.publicKey],
        })
        .accounts({
          owner: mOwner.publicKey,
          agent: mAgent.publicKey,
          policy: mPolicyPda,
          spendTracker: mTrackerPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([mOwner])
        .rpc();

      // Monitor pauses
      await program.methods
        .pauseAgent({ reason: Buffer.from("Server-triggered pause") })
        .accounts({ caller: mMonitor.publicKey, policy: mPolicyPda })
        .signers([mMonitor])
        .rpc();

      let policy = await program.account.permissionPolicy.fetch(mPolicyPda);
      expect(policy.isActive).to.be.false;
      expect(policy.pausedBy.toBase58()).to.equal(mMonitor.publicKey.toBase58());

      // Monitor tries to resume — should fail with ResumeRequiresOwner
      try {
        await program.methods
          .resumeAgent()
          .accounts({ owner: mMonitor.publicKey, policy: mPolicyPda })
          .signers([mMonitor])
          .rpc();
        expect.fail("Expected monitor resume to fail");
      } catch (err: any) {
        // has_one = owner @ ResumeRequiresOwner constraint rejects non-owner
        const errStr = err.toString();
        expect(
          errStr.includes("ResumeRequiresOwner") || errStr.includes("ConstraintHasOne")
        ).to.be.true;
      }

      // Verify still paused
      policy = await program.account.permissionPolicy.fetch(mPolicyPda);
      expect(policy.isActive).to.be.false;

      // Owner resumes successfully
      await program.methods
        .resumeAgent()
        .accounts({ owner: mOwner.publicKey, policy: mPolicyPda })
        .signers([mOwner])
        .rpc();

      policy = await program.account.permissionPolicy.fetch(mPolicyPda);
      expect(policy.isActive).to.be.true;
      expect(policy.pausedBy).to.be.null;
    });
  });

  // TODO: rotate_agent_key — stub returns NotYetImplemented (deferred to post-hackathon)
});
